### ISSUE TITLE
Couldn't find ffmpeg or avconv - defaulting to ffmpeg

### ISSUE THREAD

**Issue by finesoft2009** [SnappsiSnappes/Jarvis-free-bingGPT-voice-assistant#1]
RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

**Comment by SnappsiSnappes** [comment]
1)https://ffmpeg.org/download.html#build-windows - download ffmpeg archive 
 https://github.com/BtbN/FFmpeg-Builds/releases - win64
 2) unpack it somewhere example - C:/ffmpeg
 3) go to user environment variables   -  add user variable path to ffmpeg to PATH - create new variable
4) check it in cmd or powershell - print there 'ffmpeg' - it must return something that means it exists
![image](https://user-images.githubusercontent.com/111605401/235593908-430fd89e-b93c-43e2-8e3d-f2bbb0e3c72e.png)

**Comment by SnappsiSnappes** [comment]
btw it's very Russian project, you should change many things to convert it for  ENG...
